# This Github Action is designed to automatically publish Crate packages.
#
# While this Github Action will often be triggered, it will only publish a new package
# if the version specified in the cargo.toml file(s) is behind that already published.
#
# Further documentation on how this webhook works can be found at the following URL:
# https://github.com/marketplace/actions/publish-crates

name: "Crates Auto Publish Workflow"

on:
  workflow_call:
    inputs:
      environment:
        description: |
          Choose from which environment to run this workflow
        required: true
        type: string
      package-path:
        description: |
          Provide the path to your package.json file
        required: true
        type: string
    secrets:
      publish-token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --manifest-path ${{ inputs.package-path }}
      - name: Run tests
        run: cargo test --verbose --manifest-path ${{ inputs.package-path }}

  publish-cargo:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: publish package
        uses: katyo/publish-crates@v1
        with:
          path: ${{ inputs.package-path }}
          registry-token: ${{ secrets.publish-token }}
          ignore-unpublished-changes: true