# This Github Action is designed to automatically publish NPM packages.
#
# While this Github Action will often be triggered, it will only publish a new package
# if the version specified in the package.json file(s) is behind that already published.
#
# Further documentation on how this webhook works can be found at the following URL:
# https://github.com/marketplace/actions/npm-publish

name: "NPM Auto Publish Workflow"

on:
  workflow_call:
    inputs:
      environment:
        description: |
          Choose from which environment to run this workflow
        required: true
        type: string
      production-branch:
        description: |
          Changes pushed to this branch will always be tagged with a "latest" tag
          Any other branch will default to receiving an "alpha" tag.
        required: true
        type: string
      root-directory:
        description: |
          Provide the path to your package's root working directory
        required: true
        type: string
      package-path:
        description: |
          Provide the path to your package.json file
        required: true
        type: string
    secrets:
      publish-token:
        required: true

jobs:
  publish-npm:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Extract Tag Value
        id: extract-tag-value
        shell: bash
        run: |
          if [ "${GITHUB_REF##*/}" == "${{ inputs.production-branch }}" ]; then
            echo "Using 'Latest' Tag"
            echo "tag-value=latest" >> $GITHUB_OUTPUT
          else
            echo "Using 'Beta' Tag"
            echo "tag-value=beta" >> $GITHUB_OUTPUT
          fi

        # YARN workspaces should not be used when publishing individual packages out of a monorepo.
        # Workspaces are convenient for development as they link and share local files.
        # When publishing, however, we want to disable workspaces and force dependencies to be imported from NPM.
        # This prevents releasing packages which can build in our workspace, but not in a standalone environment.
        #
        # More details are captured in the 'Limitations & Caveats' section on:
        # https://classic.yarnpkg.com/lang/en/docs/workspaces/
        #
        # Unfortunately YARN doesn't seem to provide a simple way to turn off workspaces other than to remove the
        # 'workspaces' key from the root package.json file (which is what this step performs).
      - name: Remove workspace configuration
        working-directory: ${{ inputs.root-directory }}
        run: |
          jq 'del(.workspaces)' package.json >> package-edited.json
          mv package-edited.json package.json

      - name: NPM Publish Package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.publish-token }}
          package: ${{ inputs.package-path }}
          check-version: true
          tag: ${{ steps.extract-tag-value.outputs.tag-value }}